tags:
    - name: apikey
    - name: assistants
    - name: chatmessage
    - name: chatflows-streaming
    - name: chatflows
    - name: components-credentials-icon
    - name: components-credentials
    - name: credentials
    - name: fetch-links
    - name: flow-config
    - name: internal-chatmessage
    - name: internal-prediction
    - name: ip
    - name: load-prompt
    - name: marketplaces
    - name: node-config
    - name: node-custom-function
    - name: node-icon
    - name: node-load-method
    - name: nodes
    - name: openai-assistants
    - name: openai-assistants-file
    - name: prediction
    - name: prompts-list
    - name: public-chatbotConfig
    - name: public-chatflows
    - name: tools
    - name: variables
    - name: vector
    - name: verify
    - name: version
paths:
    /apikey:
        post:
            tags:
                - apikey
        get:
            tags:
                - apikey
        put:
            tags:
                - apikey
        delete:
            tags:
                - apikey
    /assistants:
        post:
            tags:
                - assistants
        get:
            tags:
                - assistants
        put:
            tags:
                - assistants
        delete:
            tags:
                - assistants
    /assistants/{id}:
        get:
            tags:
                - assistants
    /chatmessage/{chatflowId}:
        post:
            tags:
                - chatmessage
        get:
            tags:
                - chatmessage
        delete:
            tags:
                - chatmessage
    /chatflows-streaming/{id}:
        get:
            tags:
                - chatflows-streaming
    /chatflows:
        post:
            tags:
                - chatflows
        get:
            tags:
                - chatflows
    /chatflows/{id}:
        get:
            tags:
                - chatflows
        put:
            tags:
                - chatflows
        delete:
            tags:
                - chatflows
    /chatflows/apikey/{apiKey}:
components:
    responses:
        UnauthorizedError:
            description: Access token is missing or invalid
    schemas:
        Chatflow:
            description: Retrieval for all chatflows associated to a user id have succeded
            type: object
            properties:
                id:
                    type: string
                    format: uuid
                    example: dd7d8481-81a3-407f-95f0-a2f1cb382a4b
                name:
                    type: string
                    format: varchar
                    description: About public.chatflows.name column
                flowData:
                    type: string
                    format: text
                deployed:
                    type: boolean
                isPublic:
                    type: boolean
                apikeyid:
                    type: string
                    format: varcar
                chatbotConfig:
                    type: string
                    format: text
                createdDate:
                    type: string
                    format: date-time
                updatedDate:
                    type: string
                    format: date-time
                apiConfig:
                    type: string
                    format: text
                analytic:
                    type: string
                    format: text
                category:
                    type: string
                    format: text
    requestBodies:
        Chatflow:
            description:
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/Chatflow'
    # 1) Define the security scheme type (HTTP bearer)
    securitySchemes:
        bearerAuth:
            type: http
            scheme: bearer
            bearerFormat: JWT # optional, for documentation purposes only
